### ISSUE TITLE
Tests failing for Settings

### ISSUE THREAD

**Issue by zatziky** [amio-io/amio-sdk-js#30]
I have accidentally merged the changes of https://github.com/amio-io/amio-sdk-js/issues/25 because CircleCI was not correctly displaying the state of PR. Some tests related to Settings endpoint are failing: https://circleci.com/gh/amio-io/amio-sdk-js/34

**Comment by cybairfly** [comment]
CI test failures likely caused by versioning in first case since code is outdated and environment dependency differences in second case. Working on fixes.
