### ISSUE TITLE
Distribute code in es5 

### ISSUE THREAD

**Issue by zatziky** [amio-io/amio-sdk-js#65]
NetTrade.sk asked us if we could support pre async/await Node versions. [JaroslavKrenar](https://github.com/JaroslavKrenar) suggested to transpile the lib and look for inspiration in [moize](https://github.com/planttheidea/moize) . TThx Jaroslav!

**Comment by kuceram** [comment]
It would be better to get rid of async/await code in sdk and lower node.js version.

**Comment by zatziky** [comment]
Should be handled by #76
